version: "3.8"
services:
  ui:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - back
  back:
    build: "./back"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "21017:21017"
